### ISSUE TITLE
Assignment details for module not allowing fullstops or dashes

### ISSUE THREAD

**Issue by therealdaofu** [AY2223S1-CS2103T-W12-1/tp#127]
![image](https://user-images.githubusercontent.com/97419716/197930893-b98ca484-8bff-4868-8896-a5b798acc2a5.png)

**Comment by avock** [comment]
![image](https://user-images.githubusercontent.com/76562757/198139503-9946a7ca-9d9e-42e8-8645-f62a5b4d6e31.png)

it doesn't allow spaces now too, probably a bug during one of the PRs

**Comment by Effixion** [comment]
Done with merging of PR #249.
