### ISSUE TITLE
User guide improvements

### ISSUE THREAD

**Issue by tin-jy** [AY2223S1-CS2103T-W12-1/tp#144]
Possible UG improvements

- [x] Add glossary
- [x] Better organize command summary tables
- [x] Add more FAQ
- [x] Resize screenshots
- [x] Add a 'back to top' button
- [x] Fix page formatting (Remove whitespace after PDF conversion)

**Comment by avock** [comment]
Resizing of screenshot messes up the UG layout for me, perhaps someone could try it

**Comment by therealdaofu** [comment]
all done!
