### ISSUE TITLE
Update Project AboutUs 

### ISSUE THREAD

**Issue by avock** [AY2223S1-CS2103T-W12-1/tp#15]
Update [Project AboutUs](https://github.com/AY2223S1-CS2103T-W12-1/tp/blob/master/docs/AboutUs.md) to include images and members' personal information. 

Instructions can be found [here.](https://nus-cs2103-ay2223s1.github.io/website/schedule/week7/project.html#2-update-project-website-aboutus-readme)

If completed, profile picture should appear [here.](https://nus-cs2103-ay2223s1.github.io/website/admin/teamList.html)

**Comment by Effixion** [comment]
Added PR for this issue. Just need someone to approve. Thanks!

**Comment by avock** [comment]
done for all
