### ISSUE TITLE
[PE-D][Tester B] Mess up screen size

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W12-1/tp#163]
Category:  A legitimate user behavior is not handled

When having two screens (24 inch monitor and laptop screen), extending the app to the second screen will make it bigger in nature, but when moving the app to the smaller screen again mess up the app size. It now is bigger than the small screen and cannot be resized to smaller (since resizing is disabled). This is how it looks now in my laptop screen, as seen it is cropped out.
 

![image.png](https://raw.githubusercontent.com/florentianayuwono/ped/main/files/b30d8321-b7d7-4a89-9002-c2ebb35130e2.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: florentianayuwono/ped#1

**Comment by Effixion** [comment]
Closed since issue has been solved in v1.3
