### ISSUE TITLE
[PE-D][Tester B] The module code is cropped out (cannot be seen fully)

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W12-1/tp#167]
Category: Behavior differs from the User Guide

The module code `CS2..` is cropped (cannot be seen), when launching the app for the first time.

![image.png](https://raw.githubusercontent.com/florentianayuwono/ped/main/files/40d64bd0-0198-449d-9792-3bc21c0c1500.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: florentianayuwono/ped#4

**Comment by therealdaofu** [comment]
Thanks, this has already been fixed in the lasted release(v1.3).
