### ISSUE TITLE
[PE-D][Tester D] Flaw of "find" command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W12-1/tp#170]
![Screenshot 2022-10-28 at 4.16.02 PM.png](https://raw.githubusercontent.com/lizekai-richard/ped/main/files/dd502d25-9bde-48ba-8207-8db0afe36920.png)

As in the screenshot, it's said that searching "Friday" is not the same as searching "Friday,". However, the time format of SOCompiler is `WEEKDAY, TIMESLOT`. That means if the user wants to find all modules on Friday, they have to type `find Friday,` instead of `find Friday` which is not convenient and not reasonable.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: lizekai-richard/ped#1

**Comment by therealdaofu** [comment]
Thanks. However, since there is no restriction on user input, users can just write in the format Weekday timeslot as well.
