### ISSUE TITLE
[PE-D][Tester C] Addp does not allow addition of contacts with names with s/o abbreviation

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W12-1/tp#176]
The s/o abbreviation which stands for son of is sometimes used for names of Singaporean Indians, and perhaps should be enabled to allow the user to add their full names into the manager.
![image.png](https://raw.githubusercontent.com/kangqiao322/ped/master/files/a0e1a4b2-d3fc-4ee9-b097-1db9c54bc322.png)

![image.png](https://raw.githubusercontent.com/kangqiao322/ped/master/files/8a4586ae-c142-405a-ad1a-0a79c03cf40c.png)

Steps to reproduce bug:
type addp n/Jonny s/o balakrishnan

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: kangqiao322/ped#1

**Comment by tin-jy** [comment]
Thank you for the feedback. However, we think that this may introduce complexities to the command format. Users may instead write John so Joe as a workaround
