### ISSUE TITLE
[PE-D][Tester D] No validity check for phone number

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W12-1/tp#180]
![Screenshot 2022-10-28 at 4.24.48 PM.png](https://raw.githubusercontent.com/lizekai-richard/ped/main/files/085f33d0-fe97-41ee-93ad-dbc116012eb3.png)

For the add person command, the phone number can be any sequence of numbers longer than 3 digits. Since it's for SoC, the assumption would be all phone numbers follow the Singapore phone number format, which is 8 digits. The phone number checking is good to have.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: lizekai-richard/ped#2

**Comment by tin-jy** [comment]
Thank you for the feedback. However, our group thinks it is very possible that users may want to add numbers with varying number of digits. Adding such a restriction may cause inconvenience to the user.
