### ISSUE TITLE
[PE-D][Tester A] Accepted modules is not up to date

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W12-1/tp#182]
The list of valid modules appears to not be up to date.

MA2116 Probability is not accepted but it is under its old module code of MA2216.

Given that this module is a math major core module, many people would be taking it, so this is quite a major (pun intended) issue.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Prearo/ped#3

**Comment by avock** [comment]
The list of modules is scrapped directly from LumiNUS, and for this specific case MA2116 was listed under 

1. its old module code, MA2216 as you mentioned
2. its alternate module code, ST2131 

We will be including the ability to manually update one-off cases with outdated module codes AND alternate module codes, thank you for the suggestion!
