### ISSUE TITLE
[PE-D][Tester C] User guide has double title.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W12-1/tp#185]
At the start of the user guide, the title "SOCompiler - User Guide" is repeated.

![image.png](https://raw.githubusercontent.com/kangqiao322/ped/master/files/6131b55a-536a-4836-a6e0-550c60b696c3.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: kangqiao322/ped#2

**Comment by therealdaofu** [comment]
Thanks, have fixed it in the UG.
