### ISSUE TITLE
[PE-D][Tester B] Cannot copy the result display

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W12-1/tp#192]
Category: Feature is incomplete

In the command result display, there is this `copy` feature:

![image.png](https://raw.githubusercontent.com/florentianayuwono/ped/main/files/1ad442ec-79f5-41ff-bfc5-c0e4a57f8f49.png)

However, upon clicking on it, the content is not copied. Therefore this feature is incomplete/misleading

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: florentianayuwono/ped#19

**Comment by therealdaofu** [comment]
Copy feature only works when you press the "Select All" button. It will copy all the text in the command result display.

**Comment by tin-jy** [comment]
Thank you for the feedback. This issue has been resolved.
