### ISSUE TITLE
[PE-D][Tester B] Typo in SOCompiler

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W12-1/tp#207]
![image.png](https://raw.githubusercontent.com/florentianayuwono/ped/main/files/3b3faf78-f78c-4faa-8a5c-b5a0bc116583.png)

Should be SOCompiler, right?

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: florentianayuwono/ped#24

**Comment by therealdaofu** [comment]
Thanks, have fixed the error on UG.
