### ISSUE TITLE
[PE-D][Tester B] File name not consistent socompiler or SoCompiler

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W12-1/tp#209]
UG:

![image.png](https://raw.githubusercontent.com/florentianayuwono/ped/main/files/5ab04a62-a0e7-4375-872e-a90221004cd0.png)

But the release page:

![image.png](https://raw.githubusercontent.com/florentianayuwono/ped/main/files/a053fe3a-8a81-468e-917c-9756e66ad516.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: florentianayuwono/ped#25

**Comment by therealdaofu** [comment]
Updated UG such that it displays "SoCompiler.jar" instead.
