### ISSUE TITLE
[PE-D][Tester A] UI is barely resizeable

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W12-1/tp#210]
The UI has a very large minimum size taking up almost all of my screen (2880x1800) and cannot be shrunk to, say, half a screen, so is quite intrusive.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Prearo/ped#10

**Comment by avock** [comment]
Bug was from an outdated version that was released prior to the stated time to download by prof. Irrelevant bug in the updated version.
