### ISSUE TITLE
[PE-D][Tester E] addp command does not work for contacts with the same name but different details

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W12-1/tp#217]
From the default contacts, the first contact has the name Alex Yeoh, when trying to addp a new contact with the exact same name but different details, it is not allowed even thought they are technically different people.

![image.png](https://raw.githubusercontent.com/turretDive/ped/main/files/653f6518-55eb-47fa-9feb-30c251966e98.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: turretDive/ped#5

**Comment by Effixion** [comment]
Closed this issue as it is duplicated with issue #218.
