### ISSUE TITLE
[PE-D][Tester C] EditP allows for adding duplicate email to another person

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W12-1/tp#219]
Since emails should be unique to each person, allowing a person to have the same email as another person in the list is illogical.

![image.png](https://raw.githubusercontent.com/kangqiao322/ped/master/files/b19e49a0-ac5c-490a-a179-cb016877284f.png)

Steps to reproduce bug:
- Type editp 2 e/charlotte@example.com

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: kangqiao322/ped#7

**Comment by tin-jy** [comment]
Thank you for the feedback. However, our group finds that this is not an issue that will cause software failure. It is unlikely that a user will want to add two contacts with the same email, but if they do, our group sees no reason why we should stop them.
