### ISSUE TITLE
Make hyperlink for zoom links clickable

### ISSUE THREAD

**Issue by therealdaofu** [AY2223S1-CS2103T-W12-1/tp#82]

**Comment by avock** [comment]
Added the copy feature, but will update to make the word itself clickable, more intuitive

**Comment by Effixion** [comment]
The copy feature is also quite straightforward, especially considering our target audience, who are familiar with these types of buttons.

**Comment by avock** [comment]
Alright, will continue with the button implementation.

Will close this issue
