### ISSUE TITLE
Update DG with design details

### ISSUE THREAD

**Issue by therealdaofu** [AY2223S1-CS2103T-W12-1/tp#87]
@AY2223S1-CS2103T-W12-1/developers Update here once done
- [x] #242
- [x] Yu Ting
- [x] Yingming
- [x] Jing Yao
- [x] Chun Khai

**Comment by avock** [comment]
I believe everyone here should contribute ~1 page worth of edits according to the guidelines [here](https://nus-cs2103-ay2223s1.github.io/website/schedule/week10/project.html#4-update-the-dg-with-design-details)

**Comment by avock** [comment]
not done with the diagram of my part yet, will update asap
